### PR TITLE
Resolve java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException:…

### PR DESCRIPTION
**Pull request by mhuisman**
Resolve java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException:  javax.xml.bind.JAXBException

https://github.com/spring-guides/gs-accessing-data-jpa/issues/29

here is console output after edits made:  

```Marks-MacBook-Pro:jpatest mhuisman$ mvn clean spring-boot:run
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< org.springframework:jpatest >---------------------
[INFO] Building jpatest 0.1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ jpatest ---
[INFO] Deleting /Users/mhuisman/dev/jpatest/target
[INFO] 
[INFO] >>> spring-boot-maven-plugin:2.0.5.RELEASE:run (default-cli) > test-compile @ jpatest >>>
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ jpatest ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/mhuisman/dev/jpatest/src/main/resources
[INFO] skip non existing resourceDirectory /Users/mhuisman/dev/jpatest/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ jpatest ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /Users/mhuisman/dev/jpatest/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ jpatest ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/mhuisman/dev/jpatest/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ jpatest ---
[INFO] No sources to compile
[INFO] 
[INFO] <<< spring-boot-maven-plugin:2.0.5.RELEASE:run (default-cli) < test-compile @ jpatest <<<
[INFO] 
[INFO] 
[INFO] --- spring-boot-maven-plugin:2.0.5.RELEASE:run (default-cli) @ jpatest ---

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.0.5.RELEASE)

2019-01-16 17:55:15.233  INFO 1968 --- [           main] hello.Application                        : Starting Application on Marks-MacBook-Pro.local with PID 1968 (/Users/mhuisman/dev/jpatest/target/classes started by mhuisman in /Users/mhuisman/dev/jpatest)
2019-01-16 17:55:15.237  INFO 1968 --- [           main] hello.Application                        : No active profile set, falling back to default profiles: default
2019-01-16 17:55:15.278  INFO 1968 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@6be32b8c: startup date [Wed Jan 16 17:55:15 PST 2019]; root of context hierarchy
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (file:/Users/mhuisman/.m2/repository/org/springframework/spring-core/5.0.9.RELEASE/spring-core-5.0.9.RELEASE.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2019-01-16 17:55:16.130  INFO 1968 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2019-01-16 17:55:16.292  INFO 1968 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2019-01-16 17:55:16.359  INFO 1968 --- [           main] j.LocalContainerEntityManagerFactoryBean : Building JPA container EntityManagerFactory for persistence unit 'default'
2019-01-16 17:55:16.387  INFO 1968 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [
	name: default
	...]
2019-01-16 17:55:16.474  INFO 1968 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate Core {5.2.17.Final}
2019-01-16 17:55:16.475  INFO 1968 --- [           main] org.hibernate.cfg.Environment            : HHH000206: hibernate.properties not found
2019-01-16 17:55:16.533  INFO 1968 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.0.1.Final}
2019-01-16 17:55:16.674  INFO 1968 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
2019-01-16 17:55:17.150  INFO 1968 --- [           main] o.h.t.schema.internal.SchemaCreatorImpl  : HHH000476: Executing import script 'org.hibernate.tool.schema.internal.exec.ScriptSourceInputNonExistentImpl@9755d2c'
2019-01-16 17:55:17.152  INFO 1968 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2019-01-16 17:55:17.696  INFO 1968 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2019-01-16 17:55:17.697  INFO 1968 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'dataSource' has been autodetected for JMX exposure
2019-01-16 17:55:17.700  INFO 1968 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located MBean 'dataSource': registering with JMX server as MBean [com.zaxxer.hikari:name=dataSource,type=HikariDataSource]
2019-01-16 17:55:17.712  INFO 1968 --- [           main] hello.Application                        : Started Application in 2.765 seconds (JVM running for 6.128)
2019-01-16 17:55:17.780  INFO 1968 --- [           main] hello.Application                        : Customers found with findAll():
2019-01-16 17:55:17.780  INFO 1968 --- [           main] hello.Application                        : -------------------------------
2019-01-16 17:55:17.800  INFO 1968 --- [           main] o.h.h.i.QueryTranslatorFactoryInitiator  : HHH000397: Using ASTQueryTranslatorFactory
2019-01-16 17:55:17.920  INFO 1968 --- [           main] hello.Application                        : Customer[id=1, firstName='Jack', lastName='Bauer']
2019-01-16 17:55:17.920  INFO 1968 --- [           main] hello.Application                        : Customer[id=2, firstName='Chloe', lastName='O'Brian']
2019-01-16 17:55:17.921  INFO 1968 --- [           main] hello.Application                        : Customer[id=3, firstName='Kim', lastName='Bauer']
2019-01-16 17:55:17.921  INFO 1968 --- [           main] hello.Application                        : Customer[id=4, firstName='David', lastName='Palmer']
2019-01-16 17:55:17.921  INFO 1968 --- [           main] hello.Application                        : Customer[id=5, firstName='Michelle', lastName='Dessler']
2019-01-16 17:55:17.921  INFO 1968 --- [           main] hello.Application                        : 
2019-01-16 17:55:17.927  INFO 1968 --- [           main] hello.Application                        : Customer found with findById(1L):
2019-01-16 17:55:17.928  INFO 1968 --- [           main] hello.Application                        : --------------------------------
2019-01-16 17:55:17.928  INFO 1968 --- [           main] hello.Application                        : Customer[id=1, firstName='Jack', lastName='Bauer']
2019-01-16 17:55:17.928  INFO 1968 --- [           main] hello.Application                        : 
2019-01-16 17:55:17.928  INFO 1968 --- [           main] hello.Application                        : Customer found with findByLastName('Bauer'):
2019-01-16 17:55:17.928  INFO 1968 --- [           main] hello.Application                        : --------------------------------------------
2019-01-16 17:55:17.976  INFO 1968 --- [           main] hello.Application                        : Customer[id=1, firstName='Jack', lastName='Bauer']
2019-01-16 17:55:17.976  INFO 1968 --- [           main] hello.Application                        : Customer[id=3, firstName='Kim', lastName='Bauer']
2019-01-16 17:55:17.976  INFO 1968 --- [           main] hello.Application                        : 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.356 s
[INFO] Finished at: 2019-01-16T17:55:17-08:00
[INFO] ------------------------------------------------------------------------
2019-01-16 17:55:17.983  INFO 1968 --- [       Thread-2] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@6be32b8c: startup date [Wed Jan 16 17:55:15 PST 2019]; root of context hierarchy
2019-01-16 17:55:17.986  INFO 1968 --- [       Thread-2] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2019-01-16 17:55:17.987  INFO 1968 --- [       Thread-2] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans
2019-01-16 17:55:17.988  INFO 1968 --- [       Thread-2] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2019-01-16 17:55:17.989  INFO 1968 --- [       Thread-2] .SchemaDropperImpl$DelayedDropActionImpl : HHH000477: Starting delayed drop of schema as part of SessionFactory shut-down'
2019-01-16 17:55:17.993  INFO 1968 --- [       Thread-2] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2019-01-16 17:55:17.996  INFO 1968 --- [       Thread-2] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
```

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mhuisman Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-accessing-data-jpa&pullRequestId=36)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-accessing-data-jpa&pullRequestId=36) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@mhuisman Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-accessing-data-jpa&pullRequestId=36)!

**Comment by mhuisman** [comment]
@gregturn At your convenience, thanks in advance!

**Comment by Buzzardo** [comment]
Rebased and merged from the command line. Thanks for the PR.

**Pull request closed without merging**
